# test
- hosts: localhost
  gather_facts: no

  tasks:
  - name: Sign a playbook SCM repository
    playbook.integrity.sign:
      target: "{{ repo | default('<PATH/TO/REPO>') }}"
      signature_type: "{{ sigtype | default('gpg') }}"
      private_key: "{{ key | default('') }}"   # if empty, use gpg's default keyring
    register: result
    # ignore_errors: yes

  - debug:
      var: result

